from pydantic import BaseModel, Field
from typing import List, Literal

class EvidenceInput(BaseModel):
    """
    The structured input expected from Members 3 & 4.
    """
    heuristic_score: float = Field(..., ge=0.0, le=1.0, description="Heuristic anomaly score (0=normal, 1=highly anomalous)")
    ml_probability: float = Field(..., ge=0.0, le=1.0, description="ML probability of synthetic speech (0=human, 1=AI)")
    audio_quality_score: float = Field(..., ge=0.0, le=1.0, description="Quality of audio (0=unusable, 1=perfect)")
    insufficient_audio: bool = Field(default=False, description="Flag indicating if audio is too short/noisy for reliable detection")
    heuristic_evidence: List[str] = Field(default_factory=list, description="Specific anomalies found")
    ml_evidence: List[str] = Field(default_factory=list, description="ML feature analysis")

class RiskAssessmentOutput(BaseModel):
    """
    The final decision generated by the Risk Engine.
    """
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Combined risk score out of 100")
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "INSUFFICIENT_EVIDENCE"]
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the assessment based on audio quality")
    reasons: List[str] = Field(..., description="Explainable reasons for the decision")
    recommendation: str = Field(..., description="Actionable security recommendation")